[params]
  displayName = "EN"
  isoCode = "en"
  weight = 1
  logo = "img/logo.png"
  copyright = "Â© { year } Pratik Kapoor"

[params.author]
  name = "Pratik Kapoor"

title = "strictlyoptional"
description = "Tech explorations, hardware tuning, and engineering deep-dives"
